In [2]:
#Dictionary資料型式
import pandas as pd

data = {
    '縣市': ['台北', '台北', '台北', '新竹', '新竹', '新竹'],
    '年份': [2000, 2001, 2002, 2001, 2002, 2003],
    '人口': [2.2, 2.5, 2.7, 1.1, 1.5, 2.0]
}

df1 = pd.DataFrame(data)
display(df1)

   縣市    年份   人口
0  台北  2000  2.2
1  台北  2001  2.5
2  台北  2002  2.7
3  新竹  2001  1.1
4  新竹  2002  1.5
5  新竹  2003  2.0

In [3]:
#多個相同索引Series, 可以組成1個DataFrame
display(df1['縣市'])
display(df1['年份'])
display(df1['人口'])

0    台北
1    台北
2    台北
3    新竹
4    新竹
5    新竹
Name: 縣市, dtype: object

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: 年份, dtype: int64

0    2.2
1    2.5
2    2.7
3    1.1
4    1.5
5    2.0
Name: 人口, dtype: float64

In [4]:
data = {
    '縣市': ['台北', '台北', '台北', '新竹', '新竹', '新竹'],
    '年份': [2000, 2001, 2002, 2001, 2002, 2003],
    '人口': [2.2, 2.5, 2.7, 1.1, 1.5, 2.0]
}
df2 = pd.DataFrame(data, columns=['年份', '人口', '縣市']) #columns可以用於指定所要的索引資料或更改順序
display(df2)

     年份   人口  縣市
0  2000  2.2  台北
1  2001  2.5  台北
2  2002  2.7  台北
3  2001  1.1  新竹
4  2002  1.5  新竹
5  2003  2.0  新竹

In [5]:
data = {
    '縣市': ['台北', '台北', '台北', '新竹', '新竹', '新竹'],
    '年份': [2000, 2001, 2002, 2001, 2002, 2003],
    '人口': [2.2, 2.5, 2.7, 1.1, 1.5, 2.0]
}
df3 = pd.DataFrame(data, columns=['縣市', '人口'])
display(df3)

   縣市   人口
0  台北  2.2
1  台北  2.5
2  台北  2.7
3  新竹  1.1
4  新竹  1.5
5  新竹  2.0

In [6]:
#Dictionary資料型式
data = {
    '縣市': ['台北', '台北', '台北', '新竹', '新竹', '新竹'],
    '年份': [2000, 2001, 2002, 2001, 2002, 2003],
    '人口': [2.2, 2.5, 2.7, 1.1, 1.5, 2.0]
}
df4 = pd.DataFrame(data, index=['one', 'two', 'three', 'four', 'five', 'six'])
display(df4)

       縣市    年份   人口
one    台北  2000  2.2
two    台北  2001  2.5
three  台北  2002  2.7
four   新竹  2001  1.1
five   新竹  2002  1.5
six    新竹  2003  2.0

In [7]:
#List內放入Dictionary資料型式
data = [
    {'縣市':'台北', '年份':2000, '人口':2.2},
    {'縣市':'台中', '年份':2001, '人口':1.1},
    {'縣市':'新竹', '年份':2001, '人口':1.5},
]
df5 = pd.DataFrame(data)
display(df5)

   縣市    年份   人口
0  台北  2000  2.2
1  台中  2001  1.1
2  新竹  2001  1.5

In [9]:
#二維的numpy array
import numpy as np

data = np.random.randint(50, 101, size=(50,5)) #50列5欄
scores_df = pd.DataFrame(data, columns=['國文', '英文', '數學', '地理', '歷史'], index=range(1, 51))
display(scores_df)

    國文   英文  數學  地理  歷史
1   83   53  81  86  55
2   80   86  70  55  62
3   56   53  70  84  71
4   88   78  79  76  98
5   82   56  63  55  74
6   85   61  79  63  55
7   54   50  56  81  62
8   97   89  52  64  89
9   76   59  52  65  98
10  80   59  56  84  73
11  95   58  61  94  79
12  97   95  54  53  50
13  70   83  56  53  76
14  67   85  59  63  88
15  58   54  84  70  65
16  50   51  54  60  95
17  87   78  70  80  89
18  98   56  69  69  53
19  98   77  50  97  62
20  93   90  97  70  63
21  96  100  59  84  55
22  89   65  95  91  60
23  91   73  68  73  91
24  68   85  97  72  50
25  78   85  98  78  97
26  87   73  66  56  68
27  63   97  63  78  57
28  69   99  54  89  93
29  63   96  89  73  77
30  84   82  58  94  99
31  56   80  89  61  55
32  59   65  65  51  61
33  58   59  70  58  68
34  92   96  80  84  81
35  63   80  76  72  87
36  66   71  89  81  57
37  56   61  83  89  55
38  64   85  75  96  78
39  53   65  55  60  56
40  79   73  93  82  79
41  64   58  95  85  54
42  82   56  80  68  95
43  85   96  58  59  66
44  96   56  85  72  59
45  96   88  95  79  92
46  67   75  50  98  94
47  88   64  71  63  97
48  75   64  97  67  61
49  80   77  83  87  95
50  91   66  96  57  79

In [16]:
total_series = scores_df['國文'] + scores_df['數學'] + scores_df['英文'] + scores_df['地理'] + scores_df['歷史']
display(total_series)
display(scores_df)
scores_df['總分'] = total_series #可直接追加到陣列當中新增出欄位
display(scores_df)
scores_df['平均'] = total_series / 5.0
display(scores_df)

1     358
2     353
3     334
4     419
5     330
6     343
7     303
8     391
9     350
10    352
11    387
12    349
13    338
14    362
15    331
16    310
17    404
18    345
19    384
20    413
21    394
22    400
23    396
24    372
25    436
26    350
27    358
28    404
29    398
30    417
31    341
32    301
33    313
34    433
35    378
36    364
37    344
38    398
39    289
40    406
41    356
42    381
43    364
44    368
45    450
46    384
47    383
48    364
49    422
50    389
dtype: int64

    國文   英文  數學  地理  歷史   總分
1   83   53  81  86  55  358
2   80   86  70  55  62  353
3   56   53  70  84  71  334
4   88   78  79  76  98  419
5   82   56  63  55  74  330
6   85   61  79  63  55  343
7   54   50  56  81  62  303
8   97   89  52  64  89  391
9   76   59  52  65  98  350
10  80   59  56  84  73  352
11  95   58  61  94  79  387
12  97   95  54  53  50  349
13  70   83  56  53  76  338
14  67   85  59  63  88  362
15  58   54  84  70  65  331
16  50   51  54  60  95  310
17  87   78  70  80  89  404
18  98   56  69  69  53  345
19  98   77  50  97  62  384
20  93   90  97  70  63  413
21  96  100  59  84  55  394
22  89   65  95  91  60  400
23  91   73  68  73  91  396
24  68   85  97  72  50  372
25  78   85  98  78  97  436
26  87   73  66  56  68  350
27  63   97  63  78  57  358
28  69   99  54  89  93  404
29  63   96  89  73  77  398
30  84   82  58  94  99  417
31  56   80  89  61  55  341
32  59   65  65  51  61  301
33  58   59  70  58  68  313
34  92   96  80  84  81  433
35  63   80  76  72  87  378
36  66   71  89  81  57  364
37  56   61  83  89  55  344
38  64   85  75  96  78  398
39  53   65  55  60  56  289
40  79   73  93  82  79  406
41  64   58  95  85  54  356
42  82   56  80  68  95  381
43  85   96  58  59  66  364
44  96   56  85  72  59  368
45  96   88  95  79  92  450
46  67   75  50  98  94  384
47  88   64  71  63  97  383
48  75   64  97  67  61  364
49  80   77  83  87  95  422
50  91   66  96  57  79  389

    國文   英文  數學  地理  歷史   總分
1   83   53  81  86  55  358
2   80   86  70  55  62  353
3   56   53  70  84  71  334
4   88   78  79  76  98  419
5   82   56  63  55  74  330
6   85   61  79  63  55  343
7   54   50  56  81  62  303
8   97   89  52  64  89  391
9   76   59  52  65  98  350
10  80   59  56  84  73  352
11  95   58  61  94  79  387
12  97   95  54  53  50  349
13  70   83  56  53  76  338
14  67   85  59  63  88  362
15  58   54  84  70  65  331
16  50   51  54  60  95  310
17  87   78  70  80  89  404
18  98   56  69  69  53  345
19  98   77  50  97  62  384
20  93   90  97  70  63  413
21  96  100  59  84  55  394
22  89   65  95  91  60  400
23  91   73  68  73  91  396
24  68   85  97  72  50  372
25  78   85  98  78  97  436
26  87   73  66  56  68  350
27  63   97  63  78  57  358
28  69   99  54  89  93  404
29  63   96  89  73  77  398
30  84   82  58  94  99  417
31  56   80  89  61  55  341
32  59   65  65  51  61  301
33  58   59  70  58  68  313
34  92   96  80  84  81  433
35  63   80  76  72  87  378
36  66   71  89  81  57  364
37  56   61  83  89  55  344
38  64   85  75  96  78  398
39  53   65  55  60  56  289
40  79   73  93  82  79  406
41  64   58  95  85  54  356
42  82   56  80  68  95  381
43  85   96  58  59  66  364
44  96   56  85  72  59  368
45  96   88  95  79  92  450
46  67   75  50  98  94  384
47  88   64  71  63  97  383
48  75   64  97  67  61  364
49  80   77  83  87  95  422
50  91   66  96  57  79  389

    國文   英文  數學  地理  歷史   總分    平均
1   83   53  81  86  55  358  71.6
2   80   86  70  55  62  353  70.6
3   56   53  70  84  71  334  66.8
4   88   78  79  76  98  419  83.8
5   82   56  63  55  74  330  66.0
6   85   61  79  63  55  343  68.6
7   54   50  56  81  62  303  60.6
8   97   89  52  64  89  391  78.2
9   76   59  52  65  98  350  70.0
10  80   59  56  84  73  352  70.4
11  95   58  61  94  79  387  77.4
12  97   95  54  53  50  349  69.8
13  70   83  56  53  76  338  67.6
14  67   85  59  63  88  362  72.4
15  58   54  84  70  65  331  66.2
16  50   51  54  60  95  310  62.0
17  87   78  70  80  89  404  80.8
18  98   56  69  69  53  345  69.0
19  98   77  50  97  62  384  76.8
20  93   90  97  70  63  413  82.6
21  96  100  59  84  55  394  78.8
22  89   65  95  91  60  400  80.0
23  91   73  68  73  91  396  79.2
24  68   85  97  72  50  372  74.4
25  78   85  98  78  97  436  87.2
26  87   73  66  56  68  350  70.0
27  63   97  63  78  57  358  71.6
28  69   99  54  89  93  404  80.8
29  63   96  89  73  77  398  79.6
30  84   82  58  94  99  417  83.4
31  56   80  89  61  55  341  68.2
32  59   65  65  51  61  301  60.2
33  58   59  70  58  68  313  62.6
34  92   96  80  84  81  433  86.6
35  63   80  76  72  87  378  75.6
36  66   71  89  81  57  364  72.8
37  56   61  83  89  55  344  68.8
38  64   85  75  96  78  398  79.6
39  53   65  55  60  56  289  57.8
40  79   73  93  82  79  406  81.2
41  64   58  95  85  54  356  71.2
42  82   56  80  68  95  381  76.2
43  85   96  58  59  66  364  72.8
44  96   56  85  72  59  368  73.6
45  96   88  95  79  92  450  90.0
46  67   75  50  98  94  384  76.8
47  88   64  71  63  97  383  76.6
48  75   64  97  67  61  364  72.8
49  80   77  83  87  95  422  84.4
50  91   66  96  57  79  389  77.8

In [19]:
display(scores_df.loc[10]) 
display(scores_df.iloc[9])

國文     80.0
英文     59.0
數學     56.0
地理     84.0
歷史     73.0
總分    352.0
平均     70.4
Name: 10, dtype: float64

國文     80.0
英文     59.0
數學     56.0
地理     84.0
歷史     73.0
總分    352.0
平均     70.4
Name: 10, dtype: float64

In [26]:
#slice
display(scores_df.loc[1:10])
#使用list
display(scores_df.loc[[1, 3, 5, 7, 9]])
#抓前10筆
display(scores_df.iloc[:10]) #索引型式
#抓最後10筆
display(scores_df.iloc[-10:])

    國文  英文  數學  地理  歷史   總分    平均
1   83  53  81  86  55  358  71.6
2   80  86  70  55  62  353  70.6
3   56  53  70  84  71  334  66.8
4   88  78  79  76  98  419  83.8
5   82  56  63  55  74  330  66.0
6   85  61  79  63  55  343  68.6
7   54  50  56  81  62  303  60.6
8   97  89  52  64  89  391  78.2
9   76  59  52  65  98  350  70.0
10  80  59  56  84  73  352  70.4

   國文  英文  數學  地理  歷史   總分    平均
1  83  53  81  86  55  358  71.6
3  56  53  70  84  71  334  66.8
5  82  56  63  55  74  330  66.0
7  54  50  56  81  62  303  60.6
9  76  59  52  65  98  350  70.0

    國文  英文  數學  地理  歷史   總分    平均
1   83  53  81  86  55  358  71.6
2   80  86  70  55  62  353  70.6
3   56  53  70  84  71  334  66.8
4   88  78  79  76  98  419  83.8
5   82  56  63  55  74  330  66.0
6   85  61  79  63  55  343  68.6
7   54  50  56  81  62  303  60.6
8   97  89  52  64  89  391  78.2
9   76  59  52  65  98  350  70.0
10  80  59  56  84  73  352  70.4

    國文  英文  數學  地理  歷史   總分    平均
41  64  58  95  85  54  356  71.2
42  82  56  80  68  95  381  76.2
43  85  96  58  59  66  364  72.8
44  96  56  85  72  59  368  73.6
45  96  88  95  79  92  450  90.0
46  67  75  50  98  94  384  76.8
47  88  64  71  63  97  383  76.6
48  75  64  97  67  61  364  72.8
49  80  77  83  87  95  422  84.4
50  91  66  96  57  79  389  77.8

In [27]:
from requests import Response
import requests
from io import StringIO
import csv
import pandas as pd

def get_data()->list[dict]:
    link = 'https://raw.githubusercontent.com/roberthsu2003/__2024_02_20_2_4__/main/lesson11/students.csv'
    try :
        down:Response=requests.get(link)
        
    except:
        print("Erro")
        return 1
    file:str=down.text
    b:StringIO=StringIO(file)
    cs=csv.DictReader(b)
    data:list[dict]=list(cs)
    return data

data:list[dict] = get_data()
pd.DataFrame(data)

   name height weight
0   李政成    207     42
1   艾巧夫    153     45
2   林昱芳    184     66
3   洪阿惠    162     58
4   陳淑萍    160     79
5   黃旻林    191     79
6   陳怡伶    191     52
7   周怡啟    216     40
8   臧怡君    192     65
9   林柏洋    214     56
10  吳淑惠    173     49
11  魏秋萍    207     62
12  葉志峰    209     63
13  尚偉倫    212     81
14  張莉雯    213     56
15  童建霖    166     43
16  馮耀中    202     53
17  彭虹屏    183     56
18  黃淑芬    164     86
19  黃善迪    169     87
20  邱亭君    218     57
21  游治旺    157     42
22  林瑞喬    197     76
23  童建霖    184     58
24  陳淑娟    171     65
25  林冠蕙    197     57
26  余月修    214     68
27  陳怡容    199     56
28  陳建豪    201     80
29  潘英迪    218     81
30  錢佩豪    191     55
31  林俊翔    207     58
32  程玫靖    178     57
33  黃婷婷    202     48
34  劉慧君    196     64
35  張俊傑    174     84
36  王人仰    171     78
37  趙宛真    217     76
38  游一鈺    204     57
39  方筠紹    207     87
40   戚亨    207     66
41  鄧哲榮    180     69
42  黃淑芬    182     49
43  趙家豪    175     40
44  李政成    215     64
45  尚偉倫    183     42
46  傅佳琳    168     64
47  蔡至剛    171     65
48  艾巧夫    193     51
49  陳彥治    151     64