In [4]:
import numpy as np
import pandas as pd
from pandas import Series

subjects = ['國文', '英文', '數學', '地理', '歷史']

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores, columns=subjects, index=range(1, 51))
scores_sum = scores_df.sum(axis=1)
scores_average = scores_df.mean(axis=1)

display(scores_df)

    國文  英文   數學   地理   歷史
1   91  60   67   80   87
2   69  95   67   96   78
3   81  70   84   88   85
4   75  67   54   66  100
5   57  86   65   76   83
6   80  95   75   58   95
7   55  82   72   69   58
8   78  71   63   82   88
9   87  98   71   98   89
10  72  78   88   82   90
11  96  62   66   66   98
12  82  90   82   61   62
13  59  84   80   83   86
14  52  84   64   70   50
15  65  83   57   84   62
16  90  88   95   67   85
17  50  54   96   90   51
18  97  83   51   66   60
19  77  63   90   67   63
20  93  70   78   92   89
21  81  94   96   92   82
22  79  99   78   75   71
23  88  50   71  100   87
24  78  84   72   72   60
25  51  76   55   76   78
26  59  69   75   60   96
27  50  61   52   54   79
28  78  88   80   91   97
29  62  67   81   74   69
30  79  68   99   71   88
31  60  83   70   86   64
32  87  59   83   65   91
33  91  90   70   75   73
34  52  69   50   69   97
35  91  68   56   54   96
36  52  98   66   84   84
37  89  95   65   89   84
38  70  56   65   55   70
39  90  72   56   94   58
40  69  60   83   74   72
41  81  52   79   82   84
42  77  60   86   71   54
43  97  81   93   84   98
44  82  50   65   54   54
45  64  95   78   94  100
46  94  91   52   92   90
47  99  50   95   61   96
48  62  85  100   62   82
49  56  81   51   90   54
50  84  78  100   64   86

In [3]:
from pandas import Series
#在表格底下列位新增項目
def to_statistic(value:Series) -> Series:
    return Series([value.max(),value.min(),value.mean()], index=['最高分','最低分','平均分'])
scores_df.apply(to_statistic)

         國文     英文     數學    地理      歷史
最高分  100.00  100.0  100.0  99.0  100.00
最低分   50.00   51.0   51.0  50.0   50.00
平均分   76.28   76.5   76.3  76.5   76.18